sudo: false
dist: trusty
language: cpp
addons:
  apt:
    packages:
      - make
      - automake
      - libsdl-dev
      - libsdl-image1.2-dev

script: cd source/src && make GUI=1 && make clean && make && make install && cd ../../bin && ./phys geographos 100
